### ISSUE TITLE
Sum of 2 uints decays to Bits

### ISSUE THREAD

**Issue by akeley98** [phanrahan/magma#204] opened 2018-06-26 23:57 UTC
If two uint instances are added, I expect that the result should be of type uint, but the actual type is Bits.
```
>>> import magma as m
>>> print(type(m.uint(1, 8) + m.uint(2, 8)))
Out(Bits(8))
```
This means that I get unexpected results if I chain arithmetic operators on uint types (I may get concatenation instead of the expected addition)
```
>>> m.uint(1, 8) + m.uint(2, 8) + m.uint(255, 8)
array([.O[0], .O[1], .O[2], .O[3], .O[4], .O[5], .O[6], .O[7], 1, 1, 1, 1, 1, 1, 1, 1])
>>> 
```

**Comment by leonardt** [comment] 2018-06-27 01:22
Hmm, I think your code snippet is missing a mantle import to reproduce the issue, but I see it with an `import mantle` statement before the `+` call (since mantle needs to be imported for the operator to be overloaded).

This is an issue with how the operator circuits are defined as a generic function (since bits is the most generic). I can update them to preserve the type of the original operator call (what you're requesting), that seems like better behavior.

**Comment by leonardt** [comment] 2018-06-29 22:08
With https://github.com/phanrahan/mantle/pull/77 merged, the behavior is now:

```
>>> import magma as m
>>> import mantle
>>> print(type(m.uint(1, 8) + m.uint(2, 8)))
Out(UInt(8))
```

**Closed by leonardt** 2018-06-29 22:08 UTC
